server:
  port: 8083

spring:
  application:
    name: hotels-service
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          LOWER-CASE-SERVICE-ID: true
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka